### ISSUE TITLE
Update PyPI entry

### ISSUE THREAD

**Issue by ziotom78** [zonca/quaternionarray#3]
The last version of this package available on PyPI is 0.6.1, which is almost 6 years old. That version contains a bug in the file `setup.py` that prevents the package from being installed correctly:

````python
setup(
    name = "quaternionarray",
    version = "0.6.1",
    py_modules = ['quaternionarray, test_quaternionarray'], # Here is the error
    ...)
`````

The correct version should be

````python
setup(
    name = "quaternionarray",
    version = "0.6.1",
    py_modules = ['quaternionarray', 'test_quaternionarray'], # Now it installes fine
    ...)
`````

The current version of `setup.py` is similar, but it does not install `test_quaternionarray.py` (https://github.com/zonca/quaternionarray/blob/master/setup.py#L8). So I think that the current version could be bundled straight and put on the PyPI page.

**Comment by zonca** [comment]
ok, uploaded 0.6.2

https://pypi.python.org/pypi/quaternionarray
